// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqD2mOz7Fm_M87Z0jRhh67ZSoAyPX2K8c',
    appId: '1:17368171101:web:ce93a4ab2216bc1b6403b4',
    messagingSenderId: '17368171101',
    projectId: 'casptone-14c19',
    authDomain: 'casptone-14c19.firebaseapp.com',
    storageBucket: 'casptone-14c19.appspot.com',
    measurementId: 'G-8C4KKWE2PD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa2EiKCEsduSJnpwegmX8JOiqXj5ZBPpw',
    appId: '1:17368171101:android:211b7656614580b36403b4',
    messagingSenderId: '17368171101',
    projectId: 'casptone-14c19',
    storageBucket: 'casptone-14c19.appspot.com',
  );
}
